### ISSUE TITLE
404 error on contribute link

### ISSUE THREAD

**Issue by M2vH** [dotnet/docs.de-de#56]
At Readme.md the link to contributing is not  working.

**Comment by M2vH** [comment]
the error will be found in `/doc.de-de/README.md#net-docs`.

**Comment by mairaw** [comment]
Danke @M2vH. @nokura you'd need to point to the contributing guide in our repo for the link to work since you don't have one in the localized versions.

**Comment by M2vH** [comment]
Hallo @nokura. I will fix this. Is it planned to have a translated contributing guide later?

**Comment by mairaw** [comment]
We're creating an official contributing guide here that is also translated: https://docs.microsoft.com/de-de/contribute/

**Comment by CeciAc** [comment]
Thank you for your feedback.
 
The issue was fixed.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
@CeciAc I’m reopening this because the issue is not solved. You need to copy the readme from the English repo that has an absolute URL.

**Comment by CeciAc** [comment]
Assigning this to @nokura

**Comment by nokura** [comment]
Added the link for contribute page in https://github.com/dotnet/docs.de-de/blob/live/README.md. I am closing this issue.  Thank you for your feedback.
